// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnv7o2VW3moliF36KI2i4ZtQ2sIPT_5PI',
    appId: '1:607309304666:web:89d91d32e5740cb1669963',
    messagingSenderId: '607309304666',
    projectId: 'chat-app-9d8eb',
    authDomain: 'chat-app-9d8eb.firebaseapp.com',
    storageBucket: 'chat-app-9d8eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLffY-bIMrrvD4CS2IMX-A7u0z2VERfZU',
    appId: '1:607309304666:android:d64367d9f984efab669963',
    messagingSenderId: '607309304666',
    projectId: 'chat-app-9d8eb',
    storageBucket: 'chat-app-9d8eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAgcHyS-Z_-QXI2cK1ayFGqLs9RxQvtd4',
    appId: '1:607309304666:ios:04bde9effb215721669963',
    messagingSenderId: '607309304666',
    projectId: 'chat-app-9d8eb',
    storageBucket: 'chat-app-9d8eb.firebasestorage.app',
    iosBundleId: 'com.example.messengerApp',
  );
}
